name: Basic Workflow Demo

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node: [14, 16]
        
    steps:
    - uses: actions/checkout@v2
    - name: Set up node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test    
