name: Basic Workflow Demo

on: [push]

jobs:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Set up node.js
    uses: actions/setup-node@v1
    with:
      node-version: '14'

  - name: Install dependencies
    run: npm install

  - name: Run tests
    run: npm test

  - name: Group log lines
    run:
      echo "::group::Some Grouped Logs"
      echo "Log line 1"
      echo "Log line 2"
      echo "::endgroup::"

      
